### ISSUE TITLE
[bug]: Cannot find module 'next-themes/dist/types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by taxx0r** [shadcn-ui/ui#5706]
### Describe the bug

Hello,
I have upgraded my project to next 15.0.3-canary.5 and "next-themes": "^0.4.1",

and now when I run 
`pnpm run build `

**It works with "next-themes": "^0.3.0",**

`
./src/components/theme-provider.tsx:5:41
Type error: Cannot find module 'next-themes/dist/types' or its corresponding type declarations.

  3 | import * as React from "react";
  4 | import { ThemeProvider as NextThemesProvider } from "next-themes";
> 5 | import { type ThemeProviderProps } from "next-themes/dist/types";
    |                                         ^
  6 |
  7 | export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  8 |   return <NextThemesProvider {...props}>{children}</NextThemesProvider>;`
  
  I am using the a simple code like in the examples
  
  `
  "use client";

import * as React from "react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { type ThemeProviderProps } from "next-themes/dist/types";

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
`

I am using the latest version of  "next-themes": "^0.4.1",

### Affected component/components

Theme

### How to reproduce

Just run I run 

`pnpm run build `

### System Info

```bash
Chrome latest version
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by muhammadfathurraiyan** [comment]
try this
``` typescript
"use client";

import { ThemeProvider as NextThemesProvider } from "next-themes";

type ThemeProviderProps = React.ComponentProps<typeof NextThemesProvider>;

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
```

**Comment by taxx0r** [comment]
Wow, @muhammadfathurraiyan you are lightning fast. Works like a charm.
Thank you! Have a nive day!

**Comment by DarkShark-RAz** [comment]
thanks 

> try this
> 
> ```ts
> "use client";
> 
> import { ThemeProvider as NextThemesProvider } from "next-themes";
> 
> type ThemeProviderProps = React.ComponentProps<typeof NextThemesProvider>;
> 
> export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
>   return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
> }
> ```

**Comment by mre-dev** [comment]
> try this
> 
> ```ts
> "use client";
> 
> import { ThemeProvider as NextThemesProvider } from "next-themes";
> 
> type ThemeProviderProps = React.ComponentProps<typeof NextThemesProvider>;
> 
> export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
>   return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
> }
> ```

thanks. it worked. ⚡🔥

**Comment by JinzhaoTian** [comment]
maybe this works,
```
'use client';

import {
    ThemeProvider as NextThemesProvider,
    ThemeProviderProps
} from 'next-themes';

export default function ThemeProvider({
    children,
    ...props
}: ThemeProviderProps) {
    return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
```

**Comment by jpainam** [comment]
> maybe this works,
> 
> ```js
> 'use client';
> 
> import {
>     ThemeProvider as NextThemesProvider,
>     ThemeProviderProps
> } from 'next-themes';
> 
> export default function ThemeProvider({
>     children,
>     ...props
> }: ThemeProviderProps) {
>     return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
> }
> ```

Doesn't work.
```tsx
'"next-themes"' has no exported member named 'ThemeProviderProps'. Did you mean 'ThemeProvider'?ts(2724)
```

**Comment by AurelianSpodarec** [comment]
Why does the older version not work?

This used to work:
import { type ThemeProviderProps } from 'next-themes/dist/types'``

**Comment by AurelianSpodarec** [comment]
Thanks again lol

**Comment by iamyogess** [comment]
> try this
> 
> "use client";
> 
> import { ThemeProvider as NextThemesProvider } from "next-themes";
> 
> type ThemeProviderProps = React.ComponentProps<typeof NextThemesProvider>;
> 
> export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
>   return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
> }

**_"thank you it worked"_**


"use client";

import * as React from "react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
// import { type ThemeProviderProps } from "next-themes/dist/types"
type ThemeProviderProps = React.ComponentProps<typeof NextThemesProvider>;

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
